package com.tinydeveloper.borutoapp.ui.theme

import androidx.compose.ui.unit.dp

val EXTRA_LARGE_PADDING = 40.dp
val LARGE_PADDING = 20.dp
val MEDIUM_PADDING = 16.dp
val SMALL_PADDING = 10.dp
val EXTRA_SMALL_PADDING = 6.dp
val EXTRA_EXTRA_SMALL_PADDING = 2.dp

val PAGING_INDICATOR_WIDTH = 16.dp
val PAGING_INDICATOR_SPACING = 12.dp
val HERO_ITEM_HEIGHT = 600.dp

val NAME_PLACEHOLDER_HEIGHT = 30.dp
val ABOUT_PLACEHOLDER_HEIGHT = 15.dp
val RATING_PLACEHOLDER_HEIGHT = 25.dp

val NETWORK_ERROR_ICON_SIZE = 124.dp

val TOP_APP_BAR_HEIGHT = 56.dp

val INFO_BOX_ICON_SIZE = 40.dp
val CLOSE_ICON_SIZE = 32.dp
val EXPENDED_ICON_SIZE = 16.dp
val BOTTOM_SHEET_ICON_SIZE = 72.dp

val MIN_SHEET_HEIGHT = 180.dp

val ABOUT_LIST_HEIGHT = 100.dp

val BOTTOM_SHEET_EXPENDED_RADIUS = 0.dp

val BOTTOM_SHEET_DESCRIPTION = 358.5.dp